title: josephzxy
description: Language & Tech

social:
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/josephzxy
  - title: Linkedin
    img: /assets/images/linkedin.png
    url: https://www.linkedin.com/in/josephzxy/
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:josephchuh7@gmail.com
  - title: Weibo
    img: /assets/images/weibo.ico
    url: https://weibo.com/josephzxy

avatar: /assets/images/avatar.JPG
introduction: >
  Hi! I'm Joseph who's passionate about languages and technologies.</br></br>
  The engineering ability to deliver robust projects that are well-designed, sufficiently-and-automatically-tested, clearly-documented within a reasonable amount of time is something I am always pursuing.</br></br>
  Currently, I am familiar with common Backend stacks(MySQL, Redis, Cassandra, MongoDB, RESTful API, RPC, GraphQL) with Python-specific frameworks/libs(Asyncio, Flask, Tornado, Falcon, Huey, Pytest) as well as DevOps tools/services(Ansible, Terraform, AWS, Cloudflare, CircleCI, Scalyr, Newrelic, Sentry, Pagerduty).</br></br>
  Also, I experienced in project management with Agile methodologies(Scrum) and cross-platform apps development using Flutter.</br></br>
  My next goal is to further sharpen my Backend skills by exploiting Golang and K8s. Possibilities would be explored as well to full-stack myself with JavaScript-related stacks (Node.js, Deno.js, React.js)

working:
  title: Working Experience
  timeline:
    - date: Now
    - "AmbiLabs: Backend Engineer"
    - date: 2019-07
    - ""
    - date: 2018-11
    - "The University of Hong Kong: Part-time Research Assistant"
    - date: 2017-12   

language:
  title: Languages
  list:
    - name: English
      fluency: Professional working proficiency
    - name: Mandarin
      fluency: Native or bilingual proficiency
    - name: Cantonese
      fluency: Professional working proficiency
    - name: Japanese
      fluency: Elementary proficiency
    - name: Wenzhou Dialect 温州话
      fluency: Native or bilingual proficiency
    - name: Weihai Dialect 威海话
      fluency: Native or bilingual proficiency

education:
  title: Education Background
  timeline:
    - date: 2019-05
    - "The University of Hong Kong: Master of Science in Computer Science"
    - date: 2017-06
    - "WuHan University: Bachelor of Engineering in Spatial Information & Digital Technology"
    - date: 2013-09

google_analytics: UA-45256157-13
